//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int Id { get; set; }
        public string ParentId { get; set; }
        public int SchoolId { get; set; }
        public string Password { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string FathersMailId { get; set; }
        public string MothersMailId { get; set; }
        public string NoOfChildren { get; set; }
        public string FathersMobileNumber { get; set; }
        public string MothersMobileNumber { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string FathersBloodGroup { get; set; }
        public string MothersBloodGroup { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
