//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttandance
    {
        public int Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> Attandance { get; set; }
        public Nullable<System.DateTime> AttandanceDate { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isdelete { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Note { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string SectionId { get; set; }
    }
}
