//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string MenuRights { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ForgotPasswordCode { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string OTPCode { get; set; }
        public Nullable<bool> IsOTPVerified { get; set; }
        public Nullable<System.DateTime> OTPVerifiedValidDate { get; set; }
        public Nullable<int> SchoolUser { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
    }
}
